name: CI

on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch]

permissions:
  contents: read

jobs:
  ci:
    uses: sacmia/.github/.github/workflows/flutter-ci.yml@main
    with:
      flutter-channel: stable
      working-directory: frontend
